database:
    type: postgres
    database: infect
    schema: rda_cluster_service
    hosts:
        - host: ${CLUSTER_SERVICE_DB_HOST}
          username: root
          password: ${CLUSTER_SERVICE_DB_PASSWORD}
          port: 5432
          pools:
            - read
            - write
          maxConnections: 20


service-registry:
    host: http://l.dns.porn:9000
