database:
    type: postgres
    database: ${CLUSTER_SERVICE_DB_NAME}
    schema: rda_cluster_service
    hosts:
        - host: ${CLUSTER_SERVICE_DB_HOST}
          username: ${CLUSTER_SERVICE_DB_USER}
          password: ${CLUSTER_SERVICE_DB_PASSWORD}
          port: 5432
          pools:
            - read
            - write
          maxConnections: 20


service-registry:
    host: ${SERVICE_REGISTRY_HOST}
